load('../../data/debuggingSBPD.mat');

[dataOut, tau, extraOuts] = ...
      HJIPDE_solve_localQ(data0, lxOld, lCurr, ...
        updateEpsilon, timeDisc, schemeData, ...
        minWith, HJIextraArgs);